### PR TITLE
manifest_install: Move manifest install to cnf-testsuite

### PR DESCRIPTION
**Pull request by kosstennbl**
Manifest installation method doesn't have anything common with helm Because of that it should be moved to cnf-testsuite repo. Also, InstallMethod-related code was also moved as its usage is specific to cnf-testsuite.

Refs: #2105 (https://github.com/cnti-testcatalog/testsuite/issues/2105)

### CODE REVIEW

**Comment by kosstennbl** [comment]
Should wait for the merge of https://github.com/cnti-testcatalog/testsuite/pull/2111

**Review by martin-mat — APPROVED** [review]
lgtm

**Review by horecoli — APPROVED** [review]
looks fine.

**Review by taylor — APPROVED** [review]

**Review by rich-l — APPROVED** [review]
lgtm

**Comment by taylor** [comment]
Bump.

> Should wait for the merge of [cnti-testcatalog/testsuite#2111](https://github.com/cnti-testcatalog/testsuite/pull/2111)

Merged

**Pull request merged**
